import { Post } from "../interfaces/post.interface";

export const posts: Post[] = [
    {
    id: 1,
    title: "Sunset Bliss at Balis Best Beaches",
    text: "Bali offers some of the most stunning sunsets. Relax on Seminyak Beach and enjoy the golden hues.",
    author: "Emily Carter",
    image: "https://t3.ftcdn.net/jpg/02/03/26/82/360_F_203268202_Wxy51M8jTy6S4JfGQ1czZNedBrROn95A.jpg",
    date: new Date(2025, 2, 28), 
    category: "beach",
  },
  {
    id: 2,
    title: "Hiking Through the Swiss Alps",
    text: "Experience breathtaking views and fresh mountain air as you trek through the Swiss Alps.",
    author: "John Smith",
    image: "https://media-be.chewy.com/wp-content/uploads/2020/06/17125926/adventure-cat-rio-9.jpg",
    date: new Date(2025, 2, 20), 
    category: "mountains",
  },
  {
    id: 3,
    title: "A Quiet Retreat in Tuscany",
    text: "Explore the rolling hills and vineyards of rural Tuscany, perfect for a relaxing escape.",
    author: "Sophia Martinez",
    image: "https://www.travelawaits.com/wp-content/uploads/2021/05/shutterstock_536153089.jpg?fit=1200%2C1200",
    date: new Date(2025, 1, 15), 
    category: "rural",
  },
  {
    id: 4,
    title: "A Weekend in Tokyo: City Lights & Culture",
    text: "Tokyo is a city of contrasts, where tradition meets futuristic skyscrapers.",
    author: "David Kim",
    image: "https://www.munchiecat.com/cdn/shop/articles/cats_in_japanese_cat_cafe_d6c71cd1-9c99-4c9c-9260-ad39b0391558_600x.webp?v=1705180781",
    date: new Date(2025, 2, 10), 
    category: "city",
  },
  {
    id: 5,
    title: "Carnival in Rio: A Festival Like No Other",
    text: "Join the vibrant celebrations of Rio Carnival, full of music, dance, and colorful parades.",
    author: "Lucas Oliveira",
    image: "https://img.freepik.com/premium-photo/cat-wearing-colorful-brazilian-carnival-costume-with-feathers-sequins_1358869-1565.jpg",
    date: new Date(2025, 1, 25), 
    category: "festivals",
  },
  {
    id: 6,
    title: "Exploring the Hidden Coves of Thailand",
    text: "Discover secret beaches in Thailand, where crystal-clear waters and white sand await.",
    author: "Rachel Green",
    image: "https://townsquare.media/site/396/files/2021/06/attachment-Cat-Walking-On-Beach.jpg?w=780&q=75",
    date: new Date(2025, 2, 12),
    category: "beach",
  },
  {
    id: 7,
    title: "Climbing Mount Everest: A Journey of a Lifetime",
    text: "For those seeking the ultimate adventure, Everest offers an unparalleled challenge.",
    author: "Tom Hardy",
    image: "https://i.redd.it/hrhz2nj7jpg41.jpg",
    date: new Date(2025, 2, 18), 
    category: "mountains",
  },
  {
    id: 8,
    title: "French Countryside: A Rustic Escape",
    text: "Experience the beauty of lavender fields and charming villages in Provence.",
    author: "Marie Dubois",
    image: "https://i.dailymail.co.uk/1s/2020/03/12/21/25906550-8106847-image-a-76_1584049433412.jpg",
    date: new Date(2025, 1, 20), 
    category: "rural",
  },
  {
    id: 9,
    title: "New York City: The City That Never Sleeps",
    text: "From Times Square to Central Park, New York has something for everyone.",
    author: "Jack Williams",
    image: "https://nypost.com/wp-content/uploads/sites/2/2022/07/globetrotting-cats-Times-Square_Horizontal-1.jpg",
    date: new Date(2025, 2, 5),
    category: "city",
  },
  {
    id: 10,
    title: "Oktoberfest in Munich: Beer & Traditions",
    text: "Enjoy Germany’s largest beer festival with traditional Bavarian music and food.",
    author: "Hans Schmidt",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTI2dPY4FtZCnbQaI7kLm3ZlCR6rcXoan459ktaaZyOGGADlodkM48NNnNtAp-ZEUXZufU&usqp=CAU",
    date: new Date(2025, 8, 15),
    category: "festivals",
  },
  {
    id: 11,
    title: "Snorkeling in the Maldives: A Tropical Paradise",
    text: "Swim with vibrant marine life in the clear turquoise waters of the Maldives.",
    author: "Lara Jensen",
    image: "https://assets3.thrillist.com/v1/image/2865023/638x960/scale;webp=auto;jpeg_quality=60.jpg",
    date: new Date(2025, 3, 2), 
    category: "beach",
  },
  {
    id: 12,
    title: "Discovering the Charm of Prague",
    text: "With its medieval streets and stunning architecture, Prague is a fairytale destination.",
    author: "Anna Novak",
    image: "https://traveling-cats.com/wp-content/uploads/2013/08/Cesky-Krumlov-Castle-Czech-Republic.jpg",
    date: new Date(2025, 2, 25), 
    category: "city",
  }
]