import { Post } from "../interfaces/post.interface";

export const posts: Post[] = [
   {
        id: 1,
        title: "Sunset Bliss at Bali's Best Beaches",
        preview: "Relaxing on Seminyak Beach, enjoying a breathtaking sunset with my cat Mochi and sipping fresh coconut water.",
        text: "Bali offers some of the most stunning sunsets in the world, and I was lucky to experience them with my adventurous cat, Mochi. We arrived at Seminyak Beach just in time to watch the sky transform into a mesmerizing blend of pink, orange, and gold...",
        author: "Emily Carter",
        image: "https://t3.ftcdn.net/jpg/02/03/26/82/360_F_203268202_Wxy51M8jTy6S4JfGQ1czZNedBrROn95A.jpg",
        date: new Date(2025, 2, 28),
        category: "Beach",
    },
 {
        id: 2,
        title: "Hiking Through the Swiss Alps",
        preview: "Exploring the breathtaking Swiss Alps with my cat Whiskers, enjoying alpine meadows and cozying up in a mountain cabin.",
        text: "Hiking through the Swiss Alps with my cat, Whiskers, was an unforgettable adventure. We started our journey in a small mountain village, where Whiskers immediately became the center of attention among the friendly locals. As we made our way through the alpine meadows filled with colorful wildflowers, Whiskers curiously explored the grassy paths, stopping to observe butterflies and listen to the distant sound of cowbells echoing through the valley. The fresh mountain air and breathtaking views made every step of our hike feel magical. We took breaks near crystal-clear mountain streams, where Whiskers cautiously dipped his paws in the cold water. In the evenings, we stayed in a cozy wooden cabin high in the mountains, warmed by a crackling fireplace. Whiskers curled up beside me while I sipped on a hot mug of Swiss cocoa. Looking out of the window at the starlit sky, I knew this was a journey we would never forget.",
        author: "John Smith",
        image: "https://media-be.chewy.com/wp-content/uploads/2020/06/17125926/adventure-cat-rio-9.jpg",
        date: new Date(2025, 2, 20),
        category: "Mountains",
    },
    {
        id: 3,
        title: "A Quiet Retreat in Tuscany",
        preview: "A peaceful escape to Tuscany, staying in a farmhouse, visiting vineyards, and enjoying village life with my cat Bella.",
        text: "Tuscany's rolling hills and vineyards provided the perfect setting for a peaceful retreat with my cat, Bella. We stayed in a charming rustic farmhouse surrounded by golden fields and rows of grapevines, where Bella spent her days lounging in the sun-drenched garden, watching butterflies dance in the warm breeze. Mornings were slow and filled with the aroma of freshly baked bread and rich Italian coffee as I sat on the terrace overlooking the stunning landscape. In the afternoons, we strolled through nearby villages, where locals welcomed Bella with smiles and gentle pats. We visited vineyards, where I learned about winemaking while Bella curiously sniffed the oak barrels that held the aging wines. As the sun set over the countryside, painting the sky in shades of pink and orange, we sat together by the fireplace, listening to the sounds of the crickets and feeling completely at peace with the world.",
        author: "Sophia Martinez",
        image: "https://www.travelawaits.com/wp-content/uploads/2021/05/shutterstock_536153089.jpg?fit=1200%2C1200",
        date: new Date(2025, 1, 15),
        category: "Rural",
    },
    {
        id: 4,
        title: "A Weekend in Tokyo: City Lights & Culture",
        preview: "Exploring the vibrant streets of Tokyo with my cat Tofu, visiting a cat café and experiencing the beauty of cherry blossoms.",
        text: "Exploring Tokyo with my cat, Tofu, was an adventure like no other. The moment we stepped into the bustling streets of Shibuya, Tofu was fascinated by the flashing neon lights, the endless sea of people, and the lively sounds of the city. We visited a famous cat café, where Tofu met new feline friends and enjoyed the calm atmosphere, surrounded by warm cushions and soft music. After that, we walked through Ueno Park, where cherry blossoms were in full bloom, filling the air with their delicate scent. The sight of pink petals falling gently like snow was mesmerizing. In the evening, we ventured into the historic Asakusa district, where I sampled traditional street food while Tofu curiously watched the lantern-lit stalls. As night fell, we took in the stunning view of Tokyo’s skyline from an observation deck, the city sparkling like a sea of stars, making this trip truly unforgettable.",
        author: "David Kim",
        image: "https://www.munchiecat.com/cdn/shop/articles/cats_in_japanese_cat_cafe_d6c71cd1-9c99-4c9c-9260-ad39b0391558_600x.webp?v=1705180781",
        date: new Date(2025, 2, 10),
        category: "City",
    },
    {
        id: 5,
        title: "Carnival in Rio: A Festival Like No Other",
        preview: "Dancing through Rio’s Carnival with my cat Luna, enjoying samba parades, beach sunsets, and fireworks over the ocean.",
        text: "Rio’s Carnival is a spectacle like no other, and my cat, Luna, was just as excited as I was to witness the vibrant celebrations. The energy in the air was electrifying as we made our way through the lively streets filled with people in dazzling costumes, dancing to the rhythmic beats of samba. Drummers played with unmatched passion, and the entire city pulsed with joy. Luna, perched safely in her carrier, watched the colorful feathers and sequins flash by with wide, curious eyes. We spent the afternoon at Copacabana Beach, where the golden sand met the sparkling blue ocean, and as the sun set, we watched fireworks light up the night sky, reflecting beautifully on the waves. The magic of Carnival left us with memories of music, laughter, and an unbreakable connection to the heart of Brazil.",
        author: "Lucas Oliveira",
        image: "https://img.freepik.com/premium-photo/cat-wearing-colorful-brazilian-carnival-costume-with-feathers-sequins_1358869-1565.jpg",
        date: new Date(2025, 1, 25),
        category: "Festivals",
    },
    {
        id: 6,
        title: "Exploring the Markets of Marrakech",
        preview: "Wandering through Marrakech’s vibrant souks, discovering spices, handmade crafts, and hidden courtyards with my cat Simba.",
        text: "The bustling souks of Marrakech were a feast for the senses, and my cat, Simba, was just as curious as I was about the vibrant stalls overflowing with spices, colorful textiles, and handmade lanterns. The scent of cinnamon and saffron filled the air as we wandered through the maze-like alleys, where merchants eagerly showcased their wares. Simba peered from his carrier, fascinated by the intricate patterns of the carpets and the glistening brass teapots. In a quiet hidden courtyard, we took a break, sipping sweet mint tea as a gentle breeze carried the distant sound of traditional Moroccan music. As the sun dipped behind the terracotta rooftops, casting long shadows across the city, I knew this journey had given us an incredible glimpse into the rich culture and warmth of Marrakech.",
        author: "Aisha Hassan",
        image: "https://www.shirlontheroad.com/wp-content/uploads/2021/03/30671570533_ba271b652f_k.jpg",
        date: new Date(2025, 3, 5),
        category: "City",
    },
    {
        id: 7,
        title: "Sailing the Greek Islands",
        preview: "A dreamy sailing trip across the Greek islands with my cat Apollo, visiting Santorini, Mykonos, and hidden coves.",
        text: "Sailing through the Greek islands with my cat, Apollo, was like stepping into a dream. The adventure began in Santorini, where whitewashed houses stood against the brilliant blue of the Aegean Sea. From the deck of our boat, Apollo watched the gentle waves shimmer under the sun as we made our way to Mykonos, known for its charming windmills and lively atmosphere. We explored hidden coves with crystal-clear waters, where Apollo curiously observed tiny fish swimming near the shore. Each evening, we anchored near a quiet island, enjoying the breathtaking sunset that painted the sky in shades of orange and purple. Under a canopy of stars, the peaceful sound of the waves rocking the boat made this journey a perfect escape into the beauty of the Greek islands.",
        author: "Nikos Petros",
        image: "https://pangovet.com/wp-content/uploads/2024/06/Red-cat-looks-at-the-sea-early-in-the-morning-Santorini-island-Greece-Santorines-Shutterstock-e1671124275665.jpg",
        date: new Date(2025, 4, 12),
        category: "Beach",
    },
    {
        id: 8,
        title: "Autumn in New England",
        text: "A cozy autumn road trip through New England, enjoying fall foliage, pumpkin patches, and crisp morning air with my cat Maple. We started our journey in Vermont, driving through golden forests and stopping for fresh apple cider. Maple loved sitting by the window, watching the colorful leaves swirl outside. In New Hampshire, we hiked a short trail to a scenic overlook, where Maple curiously sniffed the crisp autumn air. At night, we stayed in a charming cabin, curled up by the fireplace, enjoying the warmth after a chilly day of adventure.",
        preview: "A cozy autumn road trip through New England, enjoying fall foliage, pumpkin patches, and crisp morning air with my cat Maple.",
        author: "Emma Wilson",
        image: "https://www.usatoday.com/gcdn/authoring/authoring-images/2024/05/20/USAT/73772641007-max-the-cat-1.jpg?width=660&height=441&fit=crop&format=pjpg&auto=webp",
        date: new Date(2025, 9, 5),
        category: "Rural",
    },
    {
        id: 9,
        title: "A Safari Adventure in Kenya",
        text: "An unforgettable safari in Kenya with my cat Leo, spotting lions, elephants, and giraffes in the wild. We stayed in a beautiful eco-lodge with views of the savanna. Every morning, we set out in a jeep, guided by local experts who shared fascinating stories about the wildlife. Leo sat comfortably in his carrier, eyes wide with curiosity as he watched zebras graze nearby. As the sun set over the African plains, we enjoyed a warm dinner by the campfire while listening to the distant roar of a lion.",
        preview: "An unforgettable safari in Kenya with my cat Leo, spotting lions, elephants, and giraffes in the wild.",
        author: "Nathan Carter",
        image: "https://www.mpalalive.org/uploads/gallery/african-wildcat_gallery_7.jpg",
        date: new Date(2025, 6, 18),
        category: "Rural",
    },
    {
        id: 10,
        title: "Ice Hotel Stay in Sweden",
        text: "Spending a magical night in Sweden’s Ice Hotel with my cat Frost, surrounded by frozen sculptures and Northern Lights. The hotel was entirely made of ice, from the walls to the beds. We dressed in warm layers and explored the mesmerizing ice carvings. At night, we cozied up in thermal sleeping bags, and Frost, surprisingly, seemed to enjoy the cool temperatures. Outside, the sky lit up with dancing Northern Lights, making it a truly unforgettable experience.",
        preview: "Spending a magical night in Sweden’s Ice Hotel with my cat Frost, surrounded by frozen sculptures and Northern Lights.",
        author: "Olivia Johansson",
        image: "https://i.ytimg.com/vi/pNvGILcWS2I/hq720.jpg?sqp=-oaymwEhCK4FEIIDSFryq4qpAxMIARUAAAAAGAElAADIQj0AgKJD&rs=AOn4CLCfwqWkWb0CrrNk608PG3ZN8LopUQ",
        date: new Date(2025, 11, 22),
        category: "Rural",
    },
    {
        id: 11,
        title: "Cherry Blossom Season in Kyoto",
        text: "Experiencing the beauty of Kyoto’s cherry blossoms, visiting ancient temples, and enjoying tea ceremonies with my cat Sakura. We wandered through the famous Philosopher’s Path, where cherry petals gently floated down like pink snow. At Kiyomizu-dera Temple, we admired the breathtaking view of the city under a canopy of blossoms. In the evening, we joined a traditional tea ceremony, where Sakura sat quietly by my side as I sipped matcha. The blend of history, nature, and serenity made this trip one to remember.",
        preview: "Experiencing the beauty of Kyoto’s cherry blossoms, visiting ancient temples, and enjoying tea ceremonies with my cat Sakura.",
        author: "Hiroshi Tanaka",
        image: "https://pangovet.com/wp-content/uploads/2024/06/Cat-in-the-Japanese-arches-in-Kyoto-Fushimi-Inari-Temple_FOTOGRIN_Shutterstock.jpeg",
        date: new Date(2025, 3, 28),
        category: "City",
    },
    {
        id: 12,
        title: "Road Tripping Along the California Coast",
        text: "A scenic road trip along California’s coastline with my cat Sunny, stopping at Big Sur, Monterey, and hidden beaches. We drove along the Pacific Coast Highway, marveling at the ocean views and dramatic cliffs. Sunny loved feeling the sea breeze as we stopped at a beachside café for lunch. In Monterey, we visited the famous aquarium, where he curiously watched the fish swim by. At sunset, we found a quiet cove, where Sunny played in the sand while I enjoyed the last rays of daylight. It was a trip filled with adventure and relaxation.",
        preview: "A scenic road trip along California’s coastline with my cat Sunny, stopping at Big Sur, Monterey, and hidden beaches.",
        author: "James Miller",
        image: "https://budgetpetcare.weebly.com/uploads/2/6/3/7/26374331/can-cats-swim_orig.jpg",
        date: new Date(2025, 5, 14),
        category: "Beach",
    }
];